export function hideAll(){
    document.querySelector("#warning_repeat")?.classList.remove("flex")
    document.querySelector("#warning_repeat")?.classList.add("hidden")
    document.querySelector("#warning_len")?.classList.remove("flex")
    document.querySelector("#warning_len")?.classList.add("hidden")
    document.querySelector("#warning_data")?.classList.remove("flex")
    document.querySelector("#warning_data")?.classList.add("hidden")
    document.querySelector("#created")?.classList.remove("flex")
    document.querySelector("#created")?.classList.add("hidden")
    document.querySelector("#user_conflict")?.classList.remove("flex")
    document.querySelector("#user_conflict")?.classList.add("hidden")
    document.querySelector("#creating")?.classList.remove("flex")
    document.querySelector("#creating")?.classList.add("hidden")
    document.querySelector("#nopass")?.classList.remove("flex")
    document.querySelector("#nopass")?.classList.add("hidden")
}